from __future__ import annotations

import asyncio
import importlib.util
import socket
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


def test_compiled_requirements_match_dependency_scopes() -> None:
    requirements = {
        name: (ROOT / name).read_text(encoding="utf-8")
        for name in (
            "requirements.txt",
            "requirements-mcp.txt",
            "requirements-dev.txt",
            "requirements-docs.txt",
        )
    }

    for content in requirements.values():
        assert content.startswith("# This file was autogenerated by uv")
        assert "\ncurl-cffi==" in content
        assert "\nlxml==" in content

    assert "\nfastmcp==" not in requirements["requirements.txt"]
    assert "\nfastmcp==" in requirements["requirements-mcp.txt"]
    assert "\npytest==" in requirements["requirements-dev.txt"]
    assert "\nruff==" in requirements["requirements-dev.txt"]
    assert "\nmkdocs==" in requirements["requirements-docs.txt"]
    assert "\nmkdocstrings==" in requirements["requirements-docs.txt"]


@pytest.mark.asyncio
async def test_horizon_entrypoint_exposes_complete_server() -> None:
    spec = importlib.util.spec_from_file_location(
        "tvfinance_horizon", ROOT / "server.py"
    )
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    tools = await module.mcp.list_tools()

    assert module.SOURCE_ROOT == ROOT / "src"
    assert sys.path[0] == str(ROOT / "src")
    assert module.mcp.name == "tvfinance"
    assert len(tools) == 23


@pytest.mark.asyncio
async def test_stdio_transport_process_handshake() -> None:
    from fastmcp import Client
    from fastmcp.client.transports import StdioTransport

    transport = StdioTransport(
        command=sys.executable,
        args=["-m", "tvfinance.mcp", "--no-banner"],
        cwd=str(ROOT),
    )
    async with Client(transport) as client:
        tools = await client.list_tools()
        result = await client.call_tool(
            "get_quote_updates", {"symbols": ["NASDAQ:AAPL"], "updates": 0}
        )

    assert len(tools) == 23
    assert result.data == []


@pytest.mark.asyncio
async def test_streamable_http_transport_process_handshake() -> None:
    from fastmcp import Client

    with socket.socket() as reservation:
        reservation.bind(("127.0.0.1", 0))
        port = reservation.getsockname()[1]

    process = subprocess.Popen(
        [
            sys.executable,
            "-m",
            "tvfinance.mcp",
            "--transport",
            "streamable-http",
            "--port",
            str(port),
            "--no-banner",
        ],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    url = f"http://127.0.0.1:{port}/mcp"
    last_error: BaseException | None = None
    try:
        for _ in range(50):
            if process.poll() is not None:
                pytest.fail(f"MCP HTTP server exited with code {process.returncode}")
            try:
                async with Client(url) as client:
                    tools = await client.list_tools()
                    result = await client.call_tool(
                        "get_quote_updates",
                        {"symbols": ["NASDAQ:AAPL"], "updates": 0},
                    )
                break
            except Exception as exc:
                last_error = exc
                await asyncio.sleep(0.1)
        else:
            pytest.fail(f"MCP HTTP server did not become ready: {last_error}")

        assert len(tools) == 23
        assert result.data == []
    finally:
        process.terminate()
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=5)
