"""Typed tools for financial market data research."""

from __future__ import annotations

from tvfinance.api import (
    bonds,
    corporate_calendar,
    dividends,
    documents,
    earnings,
    economic_calendar,
    etfs,
    financials,
    forecast,
    history,
    holdings,
    ideas,
    ipo,
    news,
    news_markdown,
    option_series,
    options_chain,
    profile,
    quote,
    quotes,
    revenue,
    screener,
    search,
    technicals,
)
from tvfinance.client import AsyncClient, Client
from tvfinance.core.exceptions import TvFinanceError
from tvfinance.core.models import (
    CalendarEvent,
    Candle,
    NewsArticle,
    OptionChainRow,
    OptionContract,
    OptionSeries,
    Quote,
    ResearchData,
    ScreenerRow,
    Symbol,
    SymbolSearchResult,
)
from tvfinance.ticker import AsyncTicker, Ticker

__version__ = "2.0.0.dev0"

__all__ = [
    "AsyncClient",
    "AsyncTicker",
    "CalendarEvent",
    "Candle",
    "Client",
    "NewsArticle",
    "OptionChainRow",
    "OptionContract",
    "OptionSeries",
    "Quote",
    "ResearchData",
    "ScreenerRow",
    "Symbol",
    "SymbolSearchResult",
    "Ticker",
    "TvFinanceError",
    "__version__",
    "bonds",
    "corporate_calendar",
    "dividends",
    "documents",
    "earnings",
    "economic_calendar",
    "etfs",
    "financials",
    "forecast",
    "history",
    "holdings",
    "ideas",
    "ipo",
    "news",
    "news_markdown",
    "option_series",
    "options_chain",
    "profile",
    "quote",
    "quotes",
    "revenue",
    "screener",
    "search",
    "technicals",
]
